# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Class_add.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Class_add(object):
    def setupUi(self, Class_add):
        Class_add.setObjectName("Class_add")
        Class_add.resize(1040, 646)
        Class_add.setStyleSheet("background-image: url(:D:/PyQt/2.png);")
        self.label = QtWidgets.QLabel(Class_add)
        self.label.setGeometry(QtCore.QRect(410, 0, 661, 131))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Class_add)
        self.label_2.setGeometry(QtCore.QRect(310, 110, 211, 51))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Class_add)
        self.lineEdit.setGeometry(QtCore.QRect(510, 120, 251, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Class_add)
        self.label_3.setGeometry(QtCore.QRect(320, 160, 211, 51))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Class_add)
        self.pushButton.setGeometry(QtCore.QRect(480, 510, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Class_add)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 570, 171, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Class_add)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 570, 171, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(Class_add)
        self.label_4.setGeometry(QtCore.QRect(300, 210, 211, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Class_add)
        self.label_5.setGeometry(QtCore.QRect(300, 260, 211, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Class_add)
        self.label_6.setGeometry(QtCore.QRect(300, 310, 211, 51))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Class_add)
        self.label_7.setGeometry(QtCore.QRect(280, 370, 211, 51))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Class_add)
        self.label_9.setGeometry(QtCore.QRect(300, 430, 211, 51))
        self.label_9.setObjectName("label_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(Class_add)
        self.lineEdit_2.setGeometry(QtCore.QRect(510, 170, 251, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Class_add)
        self.lineEdit_3.setGeometry(QtCore.QRect(510, 220, 251, 31))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(Class_add)
        self.lineEdit_5.setGeometry(QtCore.QRect(510, 320, 251, 31))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Class_add)
        self.lineEdit_6.setGeometry(QtCore.QRect(510, 380, 251, 31))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(Class_add)
        self.lineEdit_4.setGeometry(QtCore.QRect(510, 270, 251, 31))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_7 = QtWidgets.QLineEdit(Class_add)
        self.lineEdit_7.setGeometry(QtCore.QRect(510, 440, 251, 31))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")

        self.retranslateUi(Class_add)
        QtCore.QMetaObject.connectSlotsByName(Class_add)

    def retranslateUi(self, Class_add):
        _translate = QtCore.QCoreApplication.translate
        Class_add.setWindowTitle(_translate("Class_add", "班级信息添加"))
        self.label.setText(_translate("Class_add", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; color:#00aaff;\">班级信息添加</span></p></body></html>"))
        self.label_2.setText(_translate("Class_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">班级号：</span></p></body></html>"))
        self.label_3.setText(_translate("Class_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">班级：</span></p></body></html>"))
        self.pushButton.setText(_translate("Class_add", "添加"))
        self.pushButton_2.setText(_translate("Class_add", "返回班级信息管理模块"))
        self.pushButton_3.setText(_translate("Class_add", "返回主菜单"))
        self.label_4.setText(_translate("Class_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">班主任：</span></p></body></html>"))
        self.label_5.setText(_translate("Class_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">教师号：</span></p></body></html>"))
        self.label_6.setText(_translate("Class_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">教室号：</span></p></body></html>"))
        self.label_7.setText(_translate("Class_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">所在院系：</span></p></body></html>"))
        self.label_9.setText(_translate("Class_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">课程号：</span></p></body></html>"))

