# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Class_change.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Class_change(object):
    def setupUi(self, Class_change):
        Class_change.setObjectName("Class_change")
        Class_change.resize(1040, 646)
        Class_change.setStyleSheet("background-image: url(:D:/PyQt/2.png);")
        self.label = QtWidgets.QLabel(Class_change)
        self.label.setGeometry(QtCore.QRect(380, 0, 661, 131))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Class_change)
        self.label_2.setGeometry(QtCore.QRect(580, 110, 211, 51))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Class_change)
        self.lineEdit.setGeometry(QtCore.QRect(710, 120, 251, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Class_change)
        self.label_3.setGeometry(QtCore.QRect(600, 160, 211, 51))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Class_change)
        self.pushButton.setGeometry(QtCore.QRect(710, 500, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Class_change)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 570, 171, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Class_change)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 570, 171, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(Class_change)
        self.label_4.setGeometry(QtCore.QRect(580, 210, 211, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Class_change)
        self.label_5.setGeometry(QtCore.QRect(580, 260, 211, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Class_change)
        self.label_6.setGeometry(QtCore.QRect(580, 310, 211, 51))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Class_change)
        self.label_7.setGeometry(QtCore.QRect(560, 360, 211, 51))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Class_change)
        self.label_9.setGeometry(QtCore.QRect(580, 420, 211, 51))
        self.label_9.setObjectName("label_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(Class_change)
        self.lineEdit_2.setGeometry(QtCore.QRect(710, 170, 251, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Class_change)
        self.lineEdit_3.setGeometry(QtCore.QRect(710, 220, 251, 31))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(Class_change)
        self.lineEdit_5.setGeometry(QtCore.QRect(710, 320, 251, 31))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Class_change)
        self.lineEdit_6.setGeometry(QtCore.QRect(710, 370, 251, 31))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(Class_change)
        self.label_8.setGeometry(QtCore.QRect(90, 100, 241, 51))
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(Class_change)
        self.lineEdit_4.setGeometry(QtCore.QRect(710, 270, 251, 31))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_10 = QtWidgets.QLabel(Class_change)
        self.label_10.setGeometry(QtCore.QRect(90, 210, 211, 51))
        self.label_10.setObjectName("label_10")
        self.pushButton_4 = QtWidgets.QPushButton(Class_change)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 520, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit = QtWidgets.QTextEdit(Class_change)
        self.textEdit.setGeometry(QtCore.QRect(90, 280, 371, 201))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.lineEdit_7 = QtWidgets.QLineEdit(Class_change)
        self.lineEdit_7.setGeometry(QtCore.QRect(710, 430, 251, 31))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Class_change)
        self.lineEdit_8.setGeometry(QtCore.QRect(90, 160, 251, 31))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")

        self.retranslateUi(Class_change)
        QtCore.QMetaObject.connectSlotsByName(Class_change)

    def retranslateUi(self, Class_change):
        _translate = QtCore.QCoreApplication.translate
        Class_change.setWindowTitle(_translate("Class_change", "班级信息修改"))
        self.label.setText(_translate("Class_change", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; color:#00aaff;\">班级信息修改</span></p></body></html>"))
        self.label_2.setText(_translate("Class_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">班级号：</span></p></body></html>"))
        self.label_3.setText(_translate("Class_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">班级：</span></p></body></html>"))
        self.pushButton.setText(_translate("Class_change", "修改"))
        self.pushButton_2.setText(_translate("Class_change", "返回班级信息管理模块"))
        self.pushButton_3.setText(_translate("Class_change", "返回主菜单"))
        self.label_4.setText(_translate("Class_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">班主任：</span></p></body></html>"))
        self.label_5.setText(_translate("Class_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">教师号：</span></p></body></html>"))
        self.label_6.setText(_translate("Class_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">教室号：</span></p></body></html>"))
        self.label_7.setText(_translate("Class_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">所在院系：</span></p></body></html>"))
        self.label_9.setText(_translate("Class_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">课程号：</span></p></body></html>"))
        self.label_8.setText(_translate("Class_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">请输入修改前的班级号：</span></p></body></html>"))
        self.label_10.setText(_translate("Class_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">修改前的教师信息：</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Class_change", "查询"))

