# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Classroom_change.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Classroom_change(object):
    def setupUi(self, Classroom_change):
        Classroom_change.setObjectName("Classroom_change")
        Classroom_change.resize(1040, 646)
        Classroom_change.setStyleSheet("background-image: url(:D:/PyQt/2.png);")
        self.label = QtWidgets.QLabel(Classroom_change)
        self.label.setGeometry(QtCore.QRect(380, 0, 661, 131))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Classroom_change)
        self.label_2.setGeometry(QtCore.QRect(580, 110, 211, 51))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Classroom_change)
        self.lineEdit.setGeometry(QtCore.QRect(710, 120, 251, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Classroom_change)
        self.label_3.setGeometry(QtCore.QRect(560, 160, 211, 51))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Classroom_change)
        self.pushButton.setGeometry(QtCore.QRect(710, 500, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Classroom_change)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 570, 171, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Classroom_change)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 570, 171, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(Classroom_change)
        self.label_4.setGeometry(QtCore.QRect(560, 210, 211, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Classroom_change)
        self.label_5.setGeometry(QtCore.QRect(580, 250, 211, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Classroom_change)
        self.label_6.setGeometry(QtCore.QRect(580, 300, 211, 51))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Classroom_change)
        self.label_7.setGeometry(QtCore.QRect(540, 360, 211, 51))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Classroom_change)
        self.label_9.setGeometry(QtCore.QRect(600, 420, 211, 51))
        self.label_9.setObjectName("label_9")
        self.radioButton = QtWidgets.QRadioButton(Classroom_change)
        self.radioButton.setGeometry(QtCore.QRect(720, 230, 115, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Classroom_change)
        self.radioButton_2.setGeometry(QtCore.QRect(870, 230, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Classroom_change)
        self.lineEdit_2.setGeometry(QtCore.QRect(710, 170, 251, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Classroom_change)
        self.lineEdit_3.setGeometry(QtCore.QRect(710, 260, 251, 31))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(Classroom_change)
        self.lineEdit_5.setGeometry(QtCore.QRect(710, 370, 251, 31))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.comboBox = QtWidgets.QComboBox(Classroom_change)
        self.comboBox.setGeometry(QtCore.QRect(710, 320, 251, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_6 = QtWidgets.QLineEdit(Classroom_change)
        self.lineEdit_6.setGeometry(QtCore.QRect(710, 430, 251, 31))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(Classroom_change)
        self.label_8.setGeometry(QtCore.QRect(90, 100, 211, 51))
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(Classroom_change)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 160, 251, 31))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_10 = QtWidgets.QLabel(Classroom_change)
        self.label_10.setGeometry(QtCore.QRect(90, 210, 211, 51))
        self.label_10.setObjectName("label_10")
        self.pushButton_4 = QtWidgets.QPushButton(Classroom_change)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 520, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit = QtWidgets.QTextEdit(Classroom_change)
        self.textEdit.setGeometry(QtCore.QRect(90, 280, 371, 201))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Classroom_change)
        QtCore.QMetaObject.connectSlotsByName(Classroom_change)

    def retranslateUi(self, Classroom_change):
        _translate = QtCore.QCoreApplication.translate
        Classroom_change.setWindowTitle(_translate("Classroom_change", "教室信息修改"))
        self.label.setText(_translate("Classroom_change", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; color:#00aaff;\">教室信息修改</span></p></body></html>"))
        self.label_2.setText(_translate("Classroom_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">教室号：</span></p></body></html>"))
        self.label_3.setText(_translate("Classroom_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">教室类型：</span></p></body></html>"))
        self.pushButton.setText(_translate("Classroom_change", "修改"))
        self.pushButton_2.setText(_translate("Classroom_change", "返回教师信息管理模块"))
        self.pushButton_3.setText(_translate("Classroom_change", "返回主菜单"))
        self.label_4.setText(_translate("Classroom_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">教室状态：</span></p></body></html>"))
        self.label_5.setText(_translate("Classroom_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">班级号：</span></p></body></html>"))
        self.label_6.setText(_translate("Classroom_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">管理员：</span></p></body></html>"))
        self.label_7.setText(_translate("Classroom_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">管理员电话：</span></p></body></html>"))
        self.label_9.setText(_translate("Classroom_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">容量：</span></p></body></html>"))
        self.radioButton.setText(_translate("Classroom_change", "被使用"))
        self.radioButton_2.setText(_translate("Classroom_change", "未被使用"))
        self.comboBox.setItemText(0, _translate("Classroom_change", "游顺滑"))
        self.comboBox.setItemText(1, _translate("Classroom_change", "赵文成"))
        self.comboBox.setItemText(2, _translate("Classroom_change", "田向群"))
        self.comboBox.setItemText(3, _translate("Classroom_change", "石婷"))
        self.comboBox.setItemText(4, _translate("Classroom_change", "李旋"))
        self.label_8.setText(_translate("Classroom_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">请输入修改前的教室号：</span></p></body></html>"))
        self.label_10.setText(_translate("Classroom_change", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">修改前的教室信息：</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Classroom_change", "查询"))

