# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Classroom_add.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Classroom_add(object):
    def setupUi(self, Classroom_add):
        Classroom_add.setObjectName("Classroom_add")
        Classroom_add.resize(1040, 646)
        Classroom_add.setStyleSheet("background-image: url(:D:/PyQt/2.png);")
        self.label = QtWidgets.QLabel(Classroom_add)
        self.label.setGeometry(QtCore.QRect(410, 0, 661, 131))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Classroom_add)
        self.label_2.setGeometry(QtCore.QRect(300, 110, 211, 51))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Classroom_add)
        self.lineEdit.setGeometry(QtCore.QRect(510, 120, 251, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Classroom_add)
        self.label_3.setGeometry(QtCore.QRect(280, 160, 211, 51))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Classroom_add)
        self.pushButton.setGeometry(QtCore.QRect(480, 510, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Classroom_add)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 570, 171, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Classroom_add)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 570, 171, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(Classroom_add)
        self.label_4.setGeometry(QtCore.QRect(280, 220, 211, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Classroom_add)
        self.label_5.setGeometry(QtCore.QRect(300, 260, 211, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Classroom_add)
        self.label_6.setGeometry(QtCore.QRect(300, 310, 211, 51))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Classroom_add)
        self.label_7.setGeometry(QtCore.QRect(260, 360, 211, 51))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Classroom_add)
        self.label_9.setGeometry(QtCore.QRect(320, 430, 211, 51))
        self.label_9.setObjectName("label_9")
        self.radioButton = QtWidgets.QRadioButton(Classroom_add)
        self.radioButton.setGeometry(QtCore.QRect(520, 240, 115, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Classroom_add)
        self.radioButton_2.setGeometry(QtCore.QRect(670, 240, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Classroom_add)
        self.lineEdit_2.setGeometry(QtCore.QRect(510, 170, 251, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Classroom_add)
        self.lineEdit_3.setGeometry(QtCore.QRect(510, 270, 251, 31))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(Classroom_add)
        self.lineEdit_5.setGeometry(QtCore.QRect(510, 380, 251, 31))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.comboBox = QtWidgets.QComboBox(Classroom_add)
        self.comboBox.setGeometry(QtCore.QRect(510, 330, 251, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_6 = QtWidgets.QLineEdit(Classroom_add)
        self.lineEdit_6.setGeometry(QtCore.QRect(510, 440, 251, 31))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.retranslateUi(Classroom_add)
        QtCore.QMetaObject.connectSlotsByName(Classroom_add)

    def retranslateUi(self, Classroom_add):
        _translate = QtCore.QCoreApplication.translate
        Classroom_add.setWindowTitle(_translate("Classroom_add", "教室信息添加"))
        self.label.setText(_translate("Classroom_add", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; color:#00aaff;\">教室信息添加</span></p></body></html>"))
        self.label_2.setText(_translate("Classroom_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">教室号：</span></p></body></html>"))
        self.label_3.setText(_translate("Classroom_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">教室类型：</span></p></body></html>"))
        self.pushButton.setText(_translate("Classroom_add", "添加"))
        self.pushButton_2.setText(_translate("Classroom_add", "返回教室信息管理模块"))
        self.pushButton_3.setText(_translate("Classroom_add", "返回主菜单"))
        self.label_4.setText(_translate("Classroom_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">教室状态：</span></p></body></html>"))
        self.label_5.setText(_translate("Classroom_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">班级号：</span></p></body></html>"))
        self.label_6.setText(_translate("Classroom_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">管理员：</span></p></body></html>"))
        self.label_7.setText(_translate("Classroom_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">管理员电话：</span></p></body></html>"))
        self.label_9.setText(_translate("Classroom_add", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">容量：</span></p></body></html>"))
        self.radioButton.setText(_translate("Classroom_add", "被使用"))
        self.radioButton_2.setText(_translate("Classroom_add", "未被使用"))
        self.comboBox.setItemText(0, _translate("Classroom_add", "游顺滑"))
        self.comboBox.setItemText(1, _translate("Classroom_add", "赵文成"))
        self.comboBox.setItemText(2, _translate("Classroom_add", "田向群"))
        self.comboBox.setItemText(3, _translate("Classroom_add", "石婷"))
        self.comboBox.setItemText(4, _translate("Classroom_add", "李旋"))

